### PR TITLE
Tricot

### PR DESCRIPTION
**Pull request by marieALaporte**
Description 
-----------------------------------------------------

Checklist 
---------------------------------------------------------------------------------------
- [ ] An OBO file generated from an OWL file
- [ ] New terms
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] Term updates
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] CHECKS
  - [ ] New variables have a parent trait ID 
    - [ ] New variables have methods and scales 
  - [ ] The OBO file has been validated
    - [ ] checked in cassavabase
    - [ ] checked CropOntology

### CODE REVIEW

**Comment by marieALaporte** [comment]
@nmenda I made the changes as @elizabetharnaud suggested in her email

**Review by nmenda — COMMENTED** [review]
I can test if it loads ok in cassava-test and merge it now, but it would be good to add definitions to all the 'block 3' new variables

**Comment by elizabetharnaud** [comment]
Additioannly, Jacob would like to see the ordinal categories in clear like for Yield: 1. Highest yield, 2. medium Yield, 3. lowest yield so requires extra time to add this

**Comment by marieALaporte** [comment]
> Additionnaly, Jacob would like to see the ordinal categories in clear like for Yield: 1. Highest yield, 2. medium Yield, 3. lowest yield so requires extra time to add this

I am not in favour of doing that, as I will create unique scale for each trait. It is like if we have different disease scales when the rating is the same but the disease change. We don't have "1=low cassava common mosaic" or "1=low cassava brown streak disease". The definition of those 2 scales are the same: 1=low=less than % of the plant affected. Similarly here, 1=highest=best of the 3 varieties.

**Comment by elizabetharnaud** [comment]
It will create a unique scale for each triat within a crop but will remain similar across crops having a Tricot trial

**Comment by elizabetharnaud** [comment]
we can also propose:  1. highest, 2.medium and 3 low ?

**Comment by marieALaporte** [comment]
> we can also propose: 1. highest, 2.medium and 3 low ?

I will change for that then. But I don't think they are different scales for each traits. This is the same scale applied to different traits

**Comment by elizabetharnaud** [comment]
Let's discuss it before we change the TDs

**Comment by marieALaporte** [comment]
@nmenda should be ok now

**Review by nmenda — APPROVED** [review]

**Pull request merged**
